name:                flume
version:             0.1.0.0
github:              "mpdairy/flume"
license:             BSD3
author:              "Matt Parker"
maintainer:          "mpdairy@gmail.com"
copyright:           "2018 Matt Parker"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mpdairy/flume#readme>

dependencies:
- base >= 4.7 && < 5
- miso
- mtl
- protolude
- stm
- text

library:
  source-dirs: src

tests:
  flam-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flume
